# Generated by Django 3.1.7 on 2023-04-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_auto_20230403_1720'),
        ('users', '0003_auto_20230404_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.hotel'),
        ),
    ]
