# Generated by Django 3.1.7 on 2023-04-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230404_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='billet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.billet'),
        ),
    ]
