# Generated by Django 3.1.7 on 2023-04-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Hotel')),
                ('price', models.BigIntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('place', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_app.hotel')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Hotel/_service')),
                ('service_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotel')),
            ],
            options={
                'verbose_name': 'Спецпредложения',
                'verbose_name_plural': 'Спецпредложения',
            },
        ),
        migrations.CreateModel(
            name='Hotel_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_image', models.ImageField(upload_to='Hotel/_number')),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_hotel_object', to='hotel_app.hotel')),
            ],
            options={
                'verbose_name': 'номера_отелей',
                'verbose_name_plural': 'номера_отелей',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_number',
            field=models.ManyToManyField(blank=True, related_name='get_hotel_number', to='hotel_app.Hotel_number'),
        ),
    ]
