# Generated by Django 3.1.7 on 2023-04-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_hotel_number_bronny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_service_to_hotel', to='hotel_app.hotel'),
        ),
    ]
