# Generated by Django 3.1.7 on 2023-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_auto_20230403_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
