# Generated by Django 3.1.7 on 2023-04-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_auto_20230403_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='hotel_to_tour',
            new_name='hotel',
        ),
    ]
