# Generated by Django 3.1.7 on 2023-04-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_auto_20230403_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_tour_object', to='hotel_app.hotel'),
        ),
    ]
