# Generated by Django 3.1.7 on 2023-04-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_auto_20230406_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_tour_object', to='hotel_app.hotel'),
            preserve_default=False,
        ),
    ]
